apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8195'
  labels:
    io.soda.service: delfin-exporter
  name: delfin-exporter
spec:
  ports:
    - name: "8195"
      port: 8195
      targetPort: 8195
  selector:
    io.soda.service: delfin-exporter
