apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.soda.service: delfin-api
  name: delfin-api
spec:
  replicas: 2
  selector:
    matchLabels:
      io.soda.service: delfin-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.soda.service: delfin-api
    spec:
      containers:
        - args:
            - api
          env:
            - name: OS_COORDINATION__BACKEND_SERVER
              value: redis:6379
            - name: OS_DEFAULT__TRANSPORT_URL
              value: rabbit://delfinuser:delfinpass@rabbitmq:5672//
          image: sodafoundation/delfin:k8s
          name: delfin-api
          ports:
            - containerPort: 8190
          resources: {}
          volumeMounts:
            - mountPath: /etc/delfin
              name: delfin-config1
            - mountPath: /var/lib/delfin
              name: delfin-lib
            - mountPath: /var/log/delfin
              name: delfin-log
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /var/log/delfin
          name: delfin-log
        - hostPath:
            path: /var/lib/delfin
          name: delfin-lib
        - name: delfin-config1
          configMap:
            name: delfin-config
status: {}
