apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.soda.service: delfin-exporter
  name: delfin-exporter
spec:
  replicas: 2
  selector:
    matchLabels:
      io.soda.service: delfin-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.soda.service: delfin-exporter
    spec:
      containers:
        - args:
            - exporter
          env:
            - name: OS_DEFAULT__TRANSPORT_URL
              value: rabbit://delfinuser:delfinpass@rabbitmq:5672//
            - name: OS_PROMETHEUS_EXPORTER__METRICS_DIR
              value: /var/lib/delfin/metrics
          image: sodafoundation/delfin:k8s
          name: delfin-exporter
          ports:
            - containerPort: 8195
          resources: {}
          volumeMounts:
            - mountPath: /etc/delfin
              name: delfin-config1
            - mountPath: /var/lib/delfin/metrics
              name: metrics-dir
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /var/lib/delfin/metrics
          name: metrics-dir
        - name: delfin-config1
          configMap:
            name: delfin-config
status: {}
