apiVersion: v1
kind: Service
metadata:
  labels:
    io.soda.service: delfin-alert
  name: delfin-alert
spec:
  ports:
    - name: "162"
      port: 162
      targetPort: 162
  selector:
    io.soda.service: delfin-alert

