apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.soda.service: redis
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      io.soda.service: redis
  strategy: {}
  template:
    metadata:
      labels:
        io.soda.service: redis
    spec:
      containers:
        - args:
            - redis-server
          image: redis
          name: redis
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
